# Generated by Django 5.2.6 on 2025-09-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("episode_id", models.IntegerField(blank=True, null=True)),
                ("director", models.CharField(blank=True, max_length=100)),
                ("producer", models.CharField(blank=True, max_length=200)),
                ("release_date", models.CharField(blank=True, max_length=20)),
                ("url", models.URLField(blank=True)),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("height", models.CharField(blank=True, max_length=50)),
                ("mass", models.CharField(blank=True, max_length=50)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("url", models.URLField(blank=True)),
                ("votes", models.IntegerField(default=0)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="api.film"
                    ),
                ),
                (
                    "starships",
                    models.ManyToManyField(
                        blank=True, related_name="pilots", to="api.starship"
                    ),
                ),
            ],
        ),
    ]
